### Numpy (Numerical Python)

> *  벡터 및 행렬 연산에 특회된 라이브러리 <br>
*  array 단위로 데이타를 관리한다. 행렬과 유사함 <br>
* pandas와 함께 데이터 분석에 많이사용된다. <br>
* 수치해석용 Python라이브러리 <br>
* 기본적으로 array단위로 관리 및 연산을 수행한다.

#### 참고 사이트
1. home : http://www.numpy.org
2. document : http://docs.scipy.org.doc
3. tutrial :
    1) http://www.scipy-lectures.org/intro/numpy/index.html <br>
    2) http://docs.scipy.org/doc/numpy/user/quickstart.html


In [1]:
# numpy를 사용하기 위해서는 import해와야 한다.
import numpy as np
# print(dir(np)) ---> 이거 다 알아야해요
np.__version__



'1.16.5'

In [10]:
# Array 정의 및 사용하기

data =[1,2,3,4,5]
print(type(data))

# numpy의 배열(ndarray) 로 변경
arr = np.array(data)
print(arr)
print(type(arr))

# upcasting  : 강제형변환    
arr1 = np.array([1,2,3,4.1])   # 4.1 때문에 나머지도 소수쩜 있게 변환값나옴
arr1


<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


array([1. , 2. , 3. , 4.1])

In [6]:
# np.array?  # --> 쭉 보라는데 봐도 모르겠네요^^ 

In [14]:
# np.shape : numpy  배열의 크기를 리턴
# np.shape?
np.shape(arr1)      # --> (4,) : 튜플로 리턴해줘여엉~ 
# print(arr1.shape) # 이렇게도댐  왜되는진 이해못함 ㅎㅎ



(4,)


### 2. 2차원배열(행렬, Matrix)  매매매매트릭스

In [21]:
# 2차원리조트
data = [[1,2,3],[4,5,6.0]]
print(data)

# 2차원 리스트를 numpy의 2차원 배열로 변환하기.
arr = np.array(data)
print(type(arr))
print(arr.shape)  # 2행 3열
print(arr) # -------------- > 이게 2차원이에영

[[1, 2, 3], [4, 5, 6.0]]
<class 'numpy.ndarray'>
(2, 3)
[[1. 2. 3.]
 [4. 5. 6.]]


In [20]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
# numpy의 data type확인
print(arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32


### Numpy 연산

#### 1. numpy shape
* numpy에서 해당 array크기를 확인할 수 있는 함수이다. 이함수는 정수를 리턴 <br>
* shape(크기)를 확인 함으로써 numpy배열에 몇개의 데이터가 있는지? 몇차원의 데이터인지를 확인한다.
* 1차원 배열일경우 '(5,)'형태로, 2차원 배열일경우는 '(3,4)' 의 형태로 리턴한다.

#### 2. numpy datatype

* int(8, 16, 32, 64)    : 부호가 있는 정수
* uint(8, 16, 32, 64)   : 부호가 없는 정수
* float(16, 32, 64, 128): 실수
* complex(64, 128, 256) : 복소수
* bool : boolean
* string_   : 문자열 
* object    : 파이썬 오브젝트 (객체)
* unicode_  : 유니코드


In [26]:
# numpy 배열의 연산
# 배열을 연산할 때는 배열의 크기가 반드시 동일해야 한다. 틀리면 에러가 발생한다.

arr1= np.array([[1,2,3],[4,5,6]])
arr2= np.array([[7,8,9],[10,11,12]])   # 만약에 여기가 [10,11,12,13] 이렇게 배열이 안맞으면 에러~! 

print(arr1 + arr2)

print("-"*40)
print(arr1 - arr2)

print("-"*40)
print(arr1 * arr2)

print("-"*40)
print(arr1 / arr2)

print("-"*40)

print(arr1 * 2)   # 각요소에 곱하기 2를 하라는 말
print(arr1 ** 2)  # 각요소에 제곱근을 하라는것 

[[ 8 10 12]
 [14 16 18]]
----------------------------------------
[[-6 -6 -6]
 [-6 -6 -6]]
----------------------------------------
[[ 7 16 27]
 [40 55 72]]
----------------------------------------
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
----------------------------------------
[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]


In [30]:
# array의 브로드캐스트
# numpy배열에서는 동일크기를 가져야지만 연산이 가능한데
# numpy에서는 broadcast라는 기능을 제공해준다. 
# 브로드캐스트라는 것은 서루 크기가 다른 넘파이 배열을 연산이 가능하도록 해주는 기능이다.

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,11,12])  # ([10,11,12]) 이렇게 생겻지만 ([10,11,12],[10,11,12])처럼해주는게 브로드캐스팅기능이다.            
print(arr1.shape)
print(arr2.shape)

print(arr1 + arr2)

(2, 3)
(3,)
[[11 13 15]
 [14 16 18]]


### Numpy Array 의 인덱싱 과 슬라이싱


넘파이에 사용되는인덱싱은 파이썬 인덱싱과 기본적으로 동일하다. <br>
Numpy의 index는 0 부터 시작한다~



In [60]:
# ?np.arange  

# np.arrage (시작,끝,스템,데이터타입)
# 기본적으로 np.arange(10)

arr1 =np.arange(10)
print(arr1)

arr1 =np.arange(10,20,2)
print(arr1)
print(arr1.dtype)


arr1 =np.arange(10,20,2,dtype='int32')
print(arr1)
print(arr1.dtype)

arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18]
int32
[10 12 14 16 18]
int32
[0 1 2 3 4 5 6 7 8 9]


In [61]:
# 인덱싱
print(arr1[0])
print(arr1[0:3])
print(arr1[:3])
print(arr1[3:])
print(arr1[:-3])
print(arr1[:])

0
[0 1 2]
[0 1 2]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8 9]


In [62]:
# 2차원 인덱싱

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print('-'*50)

# 구조 : arr2(행,요소위치) 
print(arr2[0,0])
print(arr2[0,1])
print(arr2[0,2])
print(arr2[1,0])
print(arr2[1,1])
print(arr2[1,2])
print(arr2[2,0])
print(arr2[2,1])
print(arr2[2,2])
print('-'*50)

# 2행의 요소를 전부 꺼내기
print(arr2[:])  #전체
print(arr2[2:]) #3째행 (2차원으로 보면됨)
print(arr2[2,:]) #3째행 (1차원으로 봐야함)

print('-'*50)
print(arr2[2,2])    # 2행의 3번째 요소 = 9
print(arr2[:,2])   # 모든열의 3번째요소

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
1
2
3
4
5
6
7
8
9
--------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]]
[7 8 9]
--------------------------------------------------
9
[3 6 9]


### Numpy의 함수


* zeros(n)    : n개의 배열만큼 0으로 채움
* ones(n)     : n개의 배열의 크기만큼 1로 채움 
* arange(n)   : n개의 배열크기만큼1씩 증가하는 배열을 생성

* random      : 0~1사이의 실수 한개를 난수로 리턴
* sum
* mean
    (평균;통계관련함수)
* sort
* unique
    (중복제거함수)

In [66]:
# 1) zeros()
print(np.zeros(2))
print(np.zeros(10))
print(np.zeros((3,4)))

[0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [67]:
# 2) ones()
print(np.ones(2))
print(np.ones(10))
print(np.ones((3,4)))

[1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [87]:
# 3) arange()

print(np.arange(10,20,2,dtype='int32'))

[10 12 14 16 18]


In [88]:
# 4)  random
# np.random?

arr1 = np.random.rand(5,3)
print(arr1)
print(abs(arr1))


[[0.35911784 0.44494519 0.13425205]
 [0.92195276 0.66616673 0.58454629]
 [0.74171239 0.39067159 0.29716318]
 [0.49428248 0.06162555 0.67687467]
 [0.95133834 0.95872768 0.64601527]]
[[0.35911784 0.44494519 0.13425205]
 [0.92195276 0.66616673 0.58454629]
 [0.74171239 0.39067159 0.29716318]
 [0.49428248 0.06162555 0.67687467]
 [0.95133834 0.95872768 0.64601527]]


In [ ]:
# 5)


In [89]:
# 6) square(): 각요소의 제곱근을 계산
print(np.square(arr1))

[[0.12896562 0.19797622 0.01802361]
 [0.8499969  0.44377811 0.34169437]
 [0.55013726 0.15262429 0.08830596]
 [0.24431517 0.00379771 0.45815932]
 [0.90504463 0.91915876 0.41733572]]


In [90]:
#6. exp() : 각요쇼의 무리수를 e지수로 계산
print(np.exp(arr1))

[[1.43206555 1.56040467 1.14368104]
 [2.51419523 1.94676053 1.79417677]
 [2.09952764 1.47797305 1.34603493]
 [1.63932156 1.06356402 1.96771835]
 [2.58917253 2.60837567 1.9079231 ]]


In [91]:
# 8. log() : 각 요소를 자연로그,상용로그,밑이 2인 로그
print(np.log(arr1))

[[-1.02410469 -0.80980417 -2.00803631]
 [-0.08126129 -0.4062153  -0.5369193 ]
 [-0.29879373 -0.939888   -1.21347385]
 [-0.70464811 -2.78667871 -0.39026915]
 [-0.04988551 -0.04214821 -0.43693214]]


In [92]:
# 9. log10() : 상용로그
print(np.log10(arr1))

[[-0.44476302 -0.35169348 -0.87207909]
 [-0.03529133 -0.17641706 -0.23318109]
 [-0.12976447 -0.40818817 -0.527005  ]
 [-0.30602479 -1.21023919 -0.16949174]
 [-0.021665   -0.01830473 -0.18975722]]


In [93]:
# 10. log2() : 밑이 2인 로그
print(np.log2(arr1))

[[-1.47747076 -1.16830046 -2.89698402]
 [-0.11723526 -0.5860448  -0.77461081]
 [-0.43106823 -1.35597175 -1.75067271]
 [-1.01659234 -4.02032755 -0.56303936]
 [-0.07196958 -0.06080701 -0.63035984]]


In [94]:
# 11. sign() : 각 요소의 값을 +인경우는 1, -인경우는 -1,0인경우는 0 

np.sign(arr1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [96]:
# 12. ceil()  
np.ceil(arr1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [97]:
# 13. floor()
np.floor(arr1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [98]:
# 14.isnan()
np.isnan(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [99]:
# 15. isinf()
np.isinf(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [95]:
# 16. cos(), sin(), tan(),cosh(), sinh(), tanh()   이런게 있다는것만 알아두숑~

#### 2개의 array에 적용되는 함수

In [103]:
arr1 = np.random.randn(5,3)
arr2 = np.random.randn(5,3)

print(arr1)
print()
print(arr2)

[[-1.82266597  2.31019922  0.00611218]
 [ 1.4933596  -0.86669771 -0.59263461]
 [ 1.15674568 -1.23667224 -1.36367517]
 [ 1.14106761  0.74416109  0.1930609 ]
 [-0.76546656  0.52202239  1.50444484]]

[[ 1.25606806  0.52486277 -0.20162995]
 [-1.29744319 -2.16188579  1.08493649]
 [-1.19027055 -0.05293967  0.54722679]
 [-0.81704494 -0.31675319  0.86523849]
 [-1.52269442  1.10527265 -0.63215556]]


In [101]:
# 2개의 array연산함수 (add, subtract, multiply,divide)
np.multiply(arr1,arr2)
np.add(arr1,arr2)

array([[-0.90405338,  0.71185297,  1.57864468],
       [-0.08222784, -0.24264332, -1.2597741 ],
       [-3.59711225, -0.45912535, -3.8965301 ],
       [-0.08112453, -0.95986277,  0.58840228],
       [ 0.0165541 , -1.36295561,  2.71264999]])

In [102]:
# maximum, minimum
np.maximum(arr1,arr2)               # arr1과 arr2둘중 비교하여 큰수만 가져온거

array([[-0.05580848,  0.79893391,  0.87570768],
       [ 1.14814928, -0.05527914, -0.51523722],
       [-1.54067405,  0.59479987, -1.55420337],
       [ 0.29936818, -0.16672632,  1.56724766],
       [ 0.64100394, -0.35105992,  1.63947315]])

### 통계함수

* 통계함수를 통해서 넘파이 배열의 총합 또는 평균들을 구할 때 사용
* 열의 합 또는 행의 합 등을 구할 수 있다. 

In [106]:
# 합계:  arr1의 전체 합 구할라면 sum()함수 사용

print(np.sum(arr1))  # arr1의 전체합! 
print(np.sum(arr1,axis=1))  # arr1의 다섯 행의 합
print(np.sum(arr1,axis=0))  # arr1의 세 열의 합

2.423361240771727
[ 0.49364543  0.03402727 -1.44360174  2.0782896   1.26100067]
[ 1.20304035  1.47301274 -0.25269186]


In [107]:
# 평균: mean()
print(np.mean(arr1))  # arr1의 전체 평균! 
print(np.mean(arr1,axis=1))  # arr1의 다섯 행의 평균
print(np.mean(arr1,axis=0))  # arr1의 세 열의 평균

0.16155741605144847
[ 0.16454848  0.01134242 -0.48120058  0.6927632   0.42033356]
[ 0.24060807  0.29460255 -0.05053837]


### 통계함수 : 표준편차(std), 분산(var),최소값(min),최대값(max)

In [108]:
#  표준편차(std)

print(np.std(arr1))  # arr1의 전체 표준편차! 
print(np.std(arr1,axis=1))  # arr1의 다섯 행의 표준편차
print(np.std(arr1,axis=0))  # arr1의 세 열의 표준편차

1.192813863316883
[1.69095046 1.05390032 1.15936287 0.38872483 0.92947294]
[1.3029818  1.26569138 0.94854829]


In [109]:
# 분산(var)

print(np.var(arr1))  # arr1의 전체 분산! 
print(np.var(arr1,axis=1))  # arr1의 다섯 행의 분산
print(np.var(arr1,axis=0))  # arr1의 세 열의 분산

1.4228049125209477
[2.85931347 1.11070589 1.34412226 0.15110699 0.86391994]
[1.69776156 1.60197468 0.89974386]


In [111]:
# 최소값(min),최대값(max)
print(np.min(arr1))  # arr1의 전체 최소값! 
print(np.min(arr1,axis=1))  # arr1의 다섯 행의 최소값
print(np.min(arr1,axis=0))  # arr1의 세 열의 최소값

print(np.max(arr1))  # arr1의 전체 최대값! 
print(np.max(arr1,axis=1))  # arr1의 다섯 행의 최대값
print(np.max(arr1,axis=0))  # arr1의 세 열의 최대값

-1.8226659693503944
[-1.82266597 -0.86669771 -1.36367517  0.1930609  -0.76546656]
[-1.82266597 -1.23667224 -1.36367517]
2.310199219485457
[2.31019922 1.4933596  1.15674568 1.14106761 1.50444484]
[1.4933596  2.31019922 1.50444484]


In [113]:
# 위치함수 : 최소값(argmin),최대값(argmax)이 위치한 인덱스를 리턴

print(np.argmin(arr1))
print(np.argmax(arr1))

0
1


In [115]:
# 누적함수 : 각 성분의 누적합(cumsum),누적곱(cumprod)

print(np.cumsum(arr1))
print(np.cumprod(arr1))

[-1.82266597  0.48753325  0.49364543  1.98700504  1.12030732  0.52767271
  1.68441838  0.44774614 -0.91592903  0.22513858  0.96929967  1.16236057
  0.39689401  0.9189164   2.42336124]
[-1.82266597e+00 -4.21072150e+00 -2.57367080e-02 -3.84341600e-02
  3.33107986e-02 -1.97411323e-02 -2.28354694e-02  2.82399912e-02
 -3.85101748e-02 -4.39427131e-02 -3.27004574e-02 -6.31317978e-03
  4.83252803e-03  2.52268783e-03  3.79524470e-03]


In [137]:
# 베열정렬
print(arr1)
#print(np.sort(arr1))
print()
print(np.sort(arr1)[-2])
print()
print(np.sort(arr1)[::-1])
print()
print(np.sort(arr1,axis = 1))


[[-1.82266597  2.31019922  0.00611218]
 [ 1.4933596  -0.86669771 -0.59263461]
 [ 1.15674568 -1.23667224 -1.36367517]
 [ 1.14106761  0.74416109  0.1930609 ]
 [-0.76546656  0.52202239  1.50444484]]

[0.1930609  0.74416109 1.14106761]

[[-0.76546656  0.52202239  1.50444484]
 [ 0.1930609   0.74416109  1.14106761]
 [-1.36367517 -1.23667224  1.15674568]
 [-0.86669771 -0.59263461  1.4933596 ]
 [-1.82266597  0.00611218  2.31019922]]

[[-1.82266597  0.00611218  2.31019922]
 [-0.86669771 -0.59263461  1.4933596 ]
 [-1.36367517 -1.23667224  1.15674568]
 [ 0.1930609   0.74416109  1.14106761]
 [-0.76546656  0.52202239  1.50444484]]


In [127]:
# 중복제거 : unique()
names = np.array(['도연','주연','혜진','피카추','파이리','꼬부기','도연'])
print(names)
print(np.unique(names))    # ----> 중복된건 빼줌 

['도연' '주연' '혜진' '피카추' '파이리' '꼬부기' '도연']
['꼬부기' '도연' '주연' '파이리' '피카추' '혜진']


### 데이터분석실습 - 영화평점데이터

>  http://grouplens.org/datasets/movielens

1. 데이터다운로드
2. 해체
3. 업로드


In [130]:
# 영화평점데이터 업로드 : 약 100만건
# np.loadtxt?
data =np.loadtxt('./data/movielens/ratings.dat',delimiter='::',dtype=np.int64)

In [139]:
# 넘파이배열 [행범위, 열범위] : [2:,:3]
# [start:end, start:end]
# 첫 5행만 출력
data[0:5,:]
data[1000000:1000010, :3]   # --> 산출값 = 유저아이디 /영화 /평점 순서 
data.shape
data[0:5,:]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [141]:
# 전체 평점의 평균
data[:,2]

mean_rating_total = data[:,2].mean()
mean_rating_total 

3.581564453029317

In [146]:
# 사용자id만 추출 (중복제거)
#user_ids =?? 
#user_ids # 건수

print(data[:,0])

user_ids = np.unique(data[:,0])
user_ids.shape

[   1    1    1 ... 6040 6040 6040]


(6040,)

In [169]:
#  사용자별 평점의 평균값 구하기

mean_values = []
for user_id in user_ids:
    #print(user_id,end=",")   전체유저아이디나옴
    # 첫번째 첫번째열 = 사용자아이디
    # user id 1인 행만 추출해서  저장
    data_for_user = data[data[:,0] == user_id,:]     #  in[ ] 바로아래꺼 보기
    #print(data_for_user)
    #break
    
    #2. data_for_user을 평균
    value =data_for_user[:,2].mean()
    #print(value)
    #break
    
    #3. 평균을 mean_values에 추가
    mean_values.append([user_id, value])
    #print(mean_values)
    #break
    
print(mean_values[:5])  # 다섯행만출력
print(type(mean_values))
    

[[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466]]
<class 'list'>


In [223]:
 data[ data[:,0] == 1,:] 
             #0열(인덱싱은0부터 시작하니가..)
    #숫자바까서 돌려보기

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368],
       [        1,       595,         5, 978824268],
       [        1,       938,         4, 978301752],
       [        1,      2398,         4, 978302281],
       [        1,      2918,         4, 978302124],
       [        1,      1035,         5, 978301753],
       [        1,      2791,         4, 978302188],
       [        1,      2687,         3, 978824268],
       [        1,      2018,         4, 978301777],
       [        1,      3105,         5, 97830

In [170]:
mean_array = np.array(mean_values, dtype=np.float32)
mean_array[:5]
mean_array.shape

(6040, 2)

In [171]:
# 데이터 분석결과를 파일로저장하기
#savetxt(파일이름)
np.savetxt('./data/movielens/user_ratings_mean.csv',mean_array,fmt='%.1f', delimiter=',')
#파일생성확인

### 연습문제 

* 영화별 평점을 구해서  'movie_ratings_mean.csv'로 저장
* 영화id,영화명,평균평점

* 주의사항
- movies.dat
- 3845::And God Created Woman (Et Dieu Cr la Femme) (1956)::Drama 로 수정

- 파이썬 3.x에서 ansi파일(movies_chg.dat)로 저장

In [182]:
data_user = np.loadtxt('./data/movielens/ratings.dat', delimiter='::',dtype=np.int64)
data_movie = np.loadtxt('./data/movielens/movies_chg.dat', delimiter='::',encoding='utf-8',dtype=np.str)
        

In [183]:
data_user[:5]
data_movie[:5]

array([['1', 'Toy Story (1995)', "Animation|Children's|Comedy"],
       ['2', 'Jumanji (1995)', "Adventure|Children's|Fantasy"],
       ['3', 'Grumpier Old Men (1995)', 'Comedy|Romance'],
       ['4', 'Waiting to Exhale (1995)', 'Comedy|Drama'],
       ['5', 'Father of the Bride Part II (1995)', 'Comedy']],
      dtype='<U82')

In [216]:
# 사용자가 1번인 id
#data_user[:,1]

#영화제목 조인
#data[data[:,0] == user_id, :]
#data_movie[:,0:2]

#data_movie[data_movie[:,0]== str(1193),1]

In [221]:
# 영화평점의 평균구하기

movie_ids = np.unique(data_user[:,1]) # data_user에서 영화 id중복을 제거  # data_user[:,1]모든행에 두번째라는뜻  
mean_values = [] # 영화ID, 영화제목, 평점평균

for movie_id in movie_ids:
    
    # 1.User에서 movie_id와 같은
    data_for_movie = data_user[data_user[:,1] ==movie_id, : ]  # 모든행에 첫뻔째열이 무비아이디와 같다    
    #print(data_for_movie)
    #break
    
    # 2.영화별 평균구하기
    value = data_for_movie[:,2].mean()
    #print(value)
    #break
    
    # 3.영화제목을 구하기
    movie_name =data_movie[data_movie[:,0] == str(movie_id),1]
    # print(movie_name)
    # break
    
    # 4.평균을 mean_values([영화id,영화제목,평균])
    mean_values.append([movie_id, movie_name[0].replace(",", " "), value])



print(mean_values[:5])

[[1, 'Toy Story (1995)', 4.146846413095811], [2, 'Jumanji (1995)', 3.20114122681883], [3, 'Grumpier Old Men (1995)', 3.01673640167364], [4, 'Waiting to Exhale (1995)', 2.7294117647058824], [5, 'Father of the Bride Part II (1995)', 3.0067567567567566]]


In [222]:
# 파일생성
mean_array = np.array(mean_values, dtype=np.str)
np.savetxt("./data/movielens/movie_ratings_mean.csv", mean_array, fmt="%s", delimiter=",")